import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Asish Samanta',
  description: 'Generated by NextJS',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} flex flex-col items-center`}>
        {children}
      </body>
    </html>
  );
}
